### PING API
GET http://localhost:80/v1/ping
Accept: application/json

### I AM ALIVE API
GET http://localhost:80/v1/i-am-alive
Accept: application/json

### TRACK API
POST http://localhost:80/v1/track
Content-Type: application/json

{
  "trackId": "ad722cb8-a357-11ea-8368-985aebce38dc"
}

