### PING API
GET http://localhost:80/ping
Accept: application/json

### I AM ALIVE API
GET http://localhost:80/i-am-alive
Accept: application/json

### TRACK API
GET http://localhost:80/track/c5b75d8c-a1a1-11ea-92a3-985aebce38dc
Accept: application/json

