version: '3'

services:

  netdata:
    image: netdata/netdata
    hostname: example.com
    container_name: 'hex-netdata'
    ports:
      - 19999:19999
    depends_on:
      - redis
      - rabbitmq
      - mongodb
      - influxdb
      - core
      - grafana
      - telegraf
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: 'hex-mongodb'
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./docker/mongo/data:/data
    networks:
      - backend

  elassandra:
    image: erangaeb/elassandra:6.2
    container_name: 'hex-elassandra'
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=host.docker.internal
      - CASSANDRA_SEEDS=host.docker.internal
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
      - 9200:9200
      - 9300:9300
    networks:
      - backend

  redis:
    image: redis
    container_name: 'hex-redis'
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'hex-rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - backend

  influxdb:
    image: influxdb:latest
    container_name: 'hex-influxdb'
    ports:
      - 8083:8083
      - 8086:8086
      - 8090:8090
    volumes:
      - ./docker/influxdb/data/influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_REPORTING_DISABLED: ${INFLUXDB_REPORTING_DISABLED}
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
    networks:
      - backend

  grafana:
    build: ./docker/grafana
    container_name: 'hex-grafana'
    volumes:
      - ./docker/grafana/data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - redis
      - rabbitmq
      - influxdb
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GF_AUTH_ANONYMOUS_ORG_ROLE}
      INFLUXDB_URI: ${INFLUXDB_URI}
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_USER: ${INFLUXDB_USER}
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD}
    networks:
      - backend

  telegraf:
    image: telegraf:latest
    container_name: 'hex-telegraf'
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - redis
      - rabbitmq
      - mongodb
      - influxdb
      - grafana
    depends_on:
      - redis
      - rabbitmq
      - mongodb
      - influxdb
    environment:
      INFLUXDB_URI: ${INFLUXDB_URI}
      MONGO_HOST: ${MONGO_HOST}:${MONGO_PORT}
    networks:
      - backend

  socketio-client-tool:
    image: amritb/socketio-client-tool:latest
    container_name: 'hex-socket-client'
    ports:
      - 8001:8080
    networks:
      - backend

  core:
    build:
      context: .
      args:
        PKG: core
    container_name: 'hex-core'
    restart: unless-stopped
    ports:
      - 8080:80
      - 8081:81
    depends_on:
      - redis
      - rabbitmq
      - mongodb
    volumes:
      - ./docker/application/log:/var/log/hex
    environment:
      PKG: core
      APP_ENV: ${APP_ENV}
      MONGO_URL: ${MONGO_HOST}
      REDIS_URL: ${REDIS_HOST}:${REDIS_PORT}
      RABBIT_URL: amqp://${RABBIT_USER}:${RABBIT_PASSWORD}@${RABBIT_HOST}:5672/
    networks:
      - backend

networks:
  backend: