apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: core
  name: core
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "8081"
    port: 8081
    targetPort: 81
  selector:
    io.kompose.service: core
status:
  loadBalancer: {}
