apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elassandra
  name: elassandra
spec:
  ports:
  - name: "7000"
    port: 7000
    targetPort: 7000
  - name: "7001"
    port: 7001
    targetPort: 7001
  - name: "7199"
    port: 7199
    targetPort: 7199
  - name: "9042"
    port: 9042
    targetPort: 9042
  - name: "9160"
    port: 9160
    targetPort: 9160
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    io.kompose.service: elassandra
status:
  loadBalancer: {}
