apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yaml --out ./k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: icustomer
  name: icustomer
spec:
  ports:
  - name: "1004"
    port: 1004
    targetPort: 80
  - name: "1005"
    port: 1005
    targetPort: 81
  - name: "1006"
    port: 1006
    targetPort: 82
  selector:
    io.kompose.service: icustomer
status:
  loadBalancer: {}
