### I AM ALIVE API
GET http://localhost:1001/v1/i-am-alive
Accept: application/json

### TRACK API
POST http://localhost:1001/v1/track
Content-Type: application/json

{
  "trackId": "ee069ea2-a961-11ea-a9d2-985aebce38dc"
}

