### CREATE ROOM API
POST http://localhost:80/v1/room/create
Content-Type: application/json

{
  "customer_name": "kousha",
  "room_id": 1,
  "user_id": 3
}

### ADD USER API
PATCH http://localhost:80/v1/room/add-user
Content-Type: application/json

{
  "customer_name": "kousha",
  "room_id": 1,
  "user_id": 5
}

### ADD MESSAGE API
PATCH http://localhost:80/v1/room/add-message
Content-Type: application/json

{
  "customer_name": "kousha",
  "room_id": 1,
  "user_id": 2,
  "content": "test-content-10",
  "kind": 1
}

### ADD META DATA API
PATCH http://localhost:80/v1/room/add-meta-data
Content-Type: application/json

{
  "customer_name": "kousha",
  "room_id": 1,
  "key": "key1",
  "kind": 1,
  "value": "value1"
}

### SEEN MESSAGE API
PUT http://localhost:80/v1/room/seen-message
Content-Type: application/json

{
  "customer_name": "kousha",
  "room_id": 1,
  "message_id": "010ce2fa-abf5-11ea-8321-985aebce38dc",
  "user_id": 6
}

### DELIVER MESSAGE API
PUT http://localhost:80/v1/room/deliver-message
Content-Type: application/json

{
  "customer_name": "kousha",
  "room_id": 1,
  "message_id": "010ce2fa-abf5-11ea-8321-985aebce38dc",
  "user_id": 7
}